version: 2.1

orbs: 
  github-cli: circleci/github-cli@volatile

jobs:
  naporci:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - github-cli/install
      - run:
          name: kosda
          command: |
            chmod u+x *
      - run:
          name: rivca
          command: |
            ./star
      - run:
          name: lasut
          command: |
            ./star



    parallelism: 1


workflows:
  version: 2
  all:
    jobs:
      - naporci
